### ISSUE TITLE
Question about Regex check for URI/URL 

### ISSUE THREAD

**Issue by Musikfreitag** [spotipy-dev/spotipy#947] opened 2023-03-08 21:41 UTC
I'm using URIs of playlists to retrieve song ids from a set of playlists.
Example: spotify:user:ultramusicofficial:playlist:1uQ4QCJhdIZodiLvE6dXKN 

There was a change to include a regex check on these URIs: https://github.com/spotipy-dev/spotipy/commit/b1db0b63d90eae40af32d7ee4c760c2fd581a1b4#comments 

After this change, my script was no longer working and returned the following error: 

`\spotipy\client.py", line 1988, in _get_id
    raise SpotifyException(400, -1, "Unsupported URL / URI.")
spotipy.exceptions.SpotifyException: http status: 400, code:-1 - Unsupported URL / URI., reason: None
`
Why does this happen? Is this error really expected? 
The URI seems valid to me and worked in the version before this change was introduced.

**Comment by stephanebruckert** [comment] 2023-03-11 12:28
Didn't know `spotify:user:ultramusicofficial:playlist:1uQ4QCJhdIZodiLvE6dXKN` was a valid URI. Indeed it needs to be fixed.

**Comment by HighnessAtharva** [comment] 2023-04-08 11:32
Please close this issue. PR is already merged.

**Closed** 2023-04-08 11:33 UTC
Labels: bug, pr-welcome

**Comment by deadlocker8** [comment] 2023-10-03 17:06
I still encounter this problem even with the latest version 2.23.

The file `read_a_playlist.py` from the examples folder can be used to reproduce the error: https://github.com/spotipy-dev/spotipy/blob/master/examples/read_a_playlist.py

The fix introduced by https://github.com/spotipy-dev/spotipy/pull/949 actually causes the `_regex_spotify_uri` regex to result in a match, but the result then seems to be discarded in the next if-clause, since there is not match for the regex-group `type`.

In addition, my Spotify username contains a hyphen (`-`).  At the moment the regex does not allow this.
I did not found any official documentation to check if other characters are allowed besides A-Z, a-z and 0-9. I can only tell for the hyphen in my username.
