### ISSUE TITLE
Current 2.23.0 install from pip doesn't include latest code

### ISSUE THREAD

**Issue by twointum** [spotipy-dev/spotipy#1123] opened 2024-05-28 21:32 UTC
Hello, I have tried to uninstall/reinstall multiple times. I have examined the fresh client.py file and the artist_albums function doesn't contain the include_groups parameter. It seems to be using the old code. 

Is anyone else seeing this? 

Thanks!

**Comment by dieser-niko** [comment] 2024-05-29 06:18
This is not a bug. The latest code just hasn't been released yet, but we plan to do so sometime this week.

**Comment by twointum** [comment] 2024-05-29 16:16
Awesome! I thought I was going crazy! Is there something I'm overlooking that says that the code on the site is not part of the latest release? I am not a super experienced GitHub user.

**Comment by dieser-niko** [comment] 2024-05-29 16:20
No problem. If you want to see the code for version 2.23.0 for example, you can select the tag 2.23.0 in GitHub.
Here's a direct link: https://github.com/spotipy-dev/spotipy/tree/2.23.0

**Comment by dieser-niko** [comment] 2024-05-30 12:32
Closing as it appears that your issue has been resolved.

**Closed by dieser-niko** 2024-05-30 12:32 UTC
Labels: bug
